### ISSUE TITLE
"אימפורט" Heisenbug

### ISSUE THREAD

**Issue by yehonatanz** [Tashbezaleh/Tashbezaleh#38]
Sometimes the auto-solver (aka solver) fails for some reason.
This phenomenon occurs non-deterministic, somtimes solver fails and sometime not, without clear reason.
Can be (barely) reproduced by searching "אימפורט" and "????".

**Comment by yehonatanz** [comment]
Screenshot of the error:
![image](https://cloud.githubusercontent.com/assets/12269446/8011060/25c8a804-0bbe-11e5-993a-6dc37d1efb92.png)
Test from image:
Traceback (most recent call last):
  File "D:\App Engine\lib\webapp2-2.5.2\webapp2.py", line 1535, in **call**
    rv = self.handle_exception(request, response, e)
  File "D:\App Engine\lib\webapp2-2.5.2\webapp2.py", line 1529, in **call**
    rv = self.router.dispatch(request, response)
  File "D:\App Engine\lib\webapp2-2.5.2\webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "D:\App Engine\lib\webapp2-2.5.2\webapp2.py", line 1102, in **call**
    return handler.dispatch()
  File "D:\App Engine\lib\webapp2-2.5.2\webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "D:\App Engine\lib\webapp2-2.5.2\webapp2.py", line 570, in dispatch
    return method(_args, *_kwargs)
  File "C:\Users\YZ\Documents\GitHub\Tashbezaleh\main.py", line 41, in get
    get_results(self)
  File "C:\Users\YZ\Documents\GitHub\Tashbezaleh\main.py", line 184, in get_results
    for result in solver.find(fix_encoding(definition), regex):
  File "C:\Users\YZ\Documents\GitHub\Tashbezaleh\solver.py", line 100, in find
    on_lst = find_online(definition, guess)
  File "C:\Users\YZ\Documents\GitHub\Tashbezaleh\solver.py", line 72, in find_online
    res = urllib.urlopen(urllib.unquote(h['url'])).read()
  File "D:\App Engine\google\appengine\dist27\urllib.py", line 86, in urlopen
    return opener.open(url)
  File "D:\App Engine\google\appengine\dist27\urllib.py", line 203, in open
    return getattr(self, name)(url)
  File "D:\App Engine\google\appengine\dist27\urllib.py", line 341, in open_http
    errcode, errmsg, headers = h.getreply()
  File "D:\App Engine\google\appengine\dist27\gae_override\httplib.py", line 623, in getreply
    response = self._conn.getresponse()
  File "D:\App Engine\google\appengine\dist27\gae_override\httplib.py", line 526, in getresponse
    raise HTTPException(str(e))
HTTPException: Deadline exceeded while waiting for HTTP response from URL: http://www.b144.co.il/B144_sip/members/411404134470675840130411.aspx

**Comment by yehonatanz** [comment]
Seems to be pretty well known: https://www.google.co.il/search?q=Deadline+exceeded+while+waiting+for+HTTP+response+from+URL&oq=Deadline+exceeded+while+waiting+for+HTTP+response+from+URL&aqs=chrome..69i57j0.583j0j7&sourceid=chrome&es_sm=122&ie=UTF-8

**Comment by pelegkaz** [comment]
The current solution is satisfying, issue closed.
